/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/Common/BaseModal.vue')['default']
    ButtonIcon: typeof import('./src/components/Atom/ButtonIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    NavBar: typeof import('./src/components/Layouts/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/Layouts/SideBar.vue')['default']
    ToolTip: typeof import('./src/components/Atom/ToolTip.vue')['default']
  }
}
